### ISSUE TITLE
unittests in inline docstrings?

### ISSUE THREAD

**Issue by weikang9009** [pysal/spglm#15]
It might make sense to move the [unittests in the inline docstrings](https://github.com/pysal/spglm/blob/c6863d2cab9b7589d8a565eb48de1d0581c1ddec/spglm/utils.py#L172) to [tests/](https://github.com/pysal/spglm/tree/master/spglm/tests)?

**Comment by jGaboardi** [comment]
This is [now resolved](https://github.com/pysal/spglm/blob/615d63e6c9188273159483601c35174bf57820b8/spglm/utils.py#L171).
