### ISSUE TITLE
scipy / numpy typo?

### ISSUE THREAD

**Issue by lukhamm** [pysal/spglm#2]
Hi,
just came across your code and was wondering if in your spglm/utils.py you intended to write:
`from numpy.lib._version import NumpyVersion`
instead of:
`from scipy.lib._version import NumpyVersion`
Cheers
Lukas

**Comment by TaylorOshan** [comment]
Hi Lukas,

I think you are correct. The sparse glm module was built on top of/based off of code from the statsmodels project, so I'll check it out and double check.

**Comment by TaylorOshan** [comment]
Did a quick check on the command line and 

``from numpy.lib._version import NumpyVersion``

is correct. I've just double checked from where [the code originally came](https://github.com/statsmodels/statsmodels/blob/bb1db2b460ff4c36a6f7bcbffe69cf486c56d322/statsmodels/compat/scipy.py) from and it looks like the error is there as well. Is this causing any down stream errors? I could look into opening an issue on statsmodels as well.

**Comment by lukhamm** [comment]
Hi Taylor,
thanks for checking! I came across this error when I wanted to try out the first example in spint/gravity.py. I wouldn't know about possible down stream errors, unfortunately, since I am not actually using the code but was only helping a friend with installing it. But raising the issue on statsmodels might be useful to others.

**Comment by TaylorOshan** [comment]
Apologies, might have used down stream in a confusing way there. So that big did throw an error when trying to use or install spglm/spint? It has never caused an issue before, so am just curious how to describe the issue if I open one on statsmodels.

**Comment by lukhamm** [comment]
No worries, sorry if I misunderstood you. Installing spglm and spint works fine for me. It throws an error when using the code. After installing, when I executed the following code (the first example in the spint/gravity.py module) in the python terminal
```
>>> import numpy as np
>>> import libpysal
>>> from spint.gravity import BaseGravity
>>> db = libpysal.open(libpysal.examples.get_path('nyc_bikes_ct.csv'))
>>> cost = np.array(db.by_col('tripduration')).reshape((-1,1))
>>> flows = np.array(db.by_col('count')).reshape((-1,1))
>>> model = BaseGravity(flows, cost)
>>> model.params
```
I got an error after inserting the third line `from spint.gravity import BaseGravity`:
```
File ".../spglm-master/spglm/utils.py", line 17, in <module>
    from scipy.lib._version import NumpyVersion
ImportError: No module named 'scipy.lib'
```
which led to my very first post. I hope that helps?

**Comment by TaylorOshan** [comment]
This is great, thanks! Will close this.
