### ISSUE TITLE
logistic  GLM?

### ISSUE THREAD

**Issue by lfs119** [pysal/spglm#27]
Thanks for your good job, But I noticed that Logistic GLM is absence, which mentions in the README.md, and family.py does not contain class Logisic(Family) which is parallel with class Poisson(family)、Gaussian(family). 
Looking  forward  for your reply!

**Comment by ljwolf** [comment]
I think it's sufficient to use `family=Binomial()` to get a logistic regression. ([notebook](https://github.com/pysal/spglm/blob/master/notebooks/Binomial_GLM.ipynb))

**Comment by lfs119** [comment]
Thanks a lot.
