### ISSUE TITLE
swap from `master` to `main` branch

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spglm#35]
xref: https://github.com/pysal/pysal/issues/1285, https://github.com/pysal/libpysal/issues/353

@Ziqi-Li @martinfleis, @knaaptime I will do this unless there are detractors.

**Comment by jGaboardi** [comment]
Unless I hear from anyone, I plan on making this change later today.

**Comment by martinfleis** [comment]
Go for it

**Comment by jGaboardi** [comment]
Ah! I don't the permissions... @sjsrey @ljwolf Can you grant permission to Martin, Eli, and I?

**Comment by sjsrey** [comment]
> Ah! I don't the permissions... @sjsrey @ljwolf Can you grant permission to Martin, Eli, and I?

Done.
