### ISSUE TITLE
include tests in release

### ISSUE THREAD

**Issue by ljwolf** [pysal/spglm#9]
please include the tests in the `MANIFEST.in`, since we're consuming them downstream for `pysal/pysal` now.

**Comment by TaylorOshan** [comment]
@ljwolf Based on the previous sub-module template I had been using, there was no MANIFEST.in file. Is there a sub-module you suggest for reference for a proper manifest file that includes tests?

**Comment by ljwolf** [comment]
Actually, I think it's sufficient to add an `__init__.py` to your test directory. That'll make Python understand the `tests` folder as a module.

**Comment by TaylorOshan** [comment]
Ok, seems even simpler, will do.

**Comment by TaylorOshan** [comment]
Wait, actually, I already had an ``__init__.py``. Good to go then?

**Comment by ljwolf** [comment]
hmm, if the tests are in your `tar.gz` when you run `python setup.py sdist`, then yes.

**Comment by TaylorOshan** [comment]
This should now be remedied.
